### ISSUE TITLE
#10 Meetup @ Ethereum Singapore & Token2049

### ISSUE THREAD

**Issue by ksaitor** [SoliditySingapore/meetups#10]

**Comment by ksaitor** [comment]
@alxiong [@alex_xiong_](https://twitter.com/alex_xiong_) - Espresso Sequencer (HotShot consensus, Tiramisu data availability solution)

Slides:
https://github.com/SoliditySingapore/meetups/files/12609034/Espresso-SoliditySG23.pdf

**Comment by ksaitor** [comment]
​[@Amber_hcq](https://twitter.com/Amber_hcq) - Finding bugs in zkEVM (Veridise)

https://github.com/SoliditySingapore/meetups/files/12614801/Veridise_ZKEVM.Amber.version.pdf

**Comment by bguiz** [comment]
@bguiz - Account Abstraction on EVM-compatible networks: Hedera and Ethereum
https://blog.bguiz.com/presentations/evm-account-abstraction-hedera-ethereum/
(Press `F` or full screen, and `S` for speaker notes)

Here's [a tweet thread](https://twitter.com/bguiz/status/1701928993287819330) about it.

and [video](https://www.youtube.com/watch?v=6YOeXyAuMXk)

**Comment by ksaitor** [comment]
Suede Kam - Hyper Oracle - Secure and Trustless Oracle via ZK
Twitter: https://x.com/hyperoracle
Github: https://github.com/hyperoracle

[Solidity - Secure and Trustless Oracle via ZK.pdf](https://github.com/SoliditySingapore/meetups/files/12644160/Solidity.-.Secure.and.Trustless.Oracle.via.ZK.pdf)

**Comment by ksaitor** [comment]
@agnxsh

Verkle Tries, Statelessness and The Verge
https://github.com/SoliditySingapore/meetups/files/12644375/Verkle.Tries.Statelessness.and.The.Verge.pdf

**Comment by ksaitor** [comment]
Gas Optimization with Solady https://github.com/Vectorized/solady 
@Vectorized 
https://github.com/SoliditySingapore/meetups/files/12655729/solady_solidity_singapore.pdf
