### ISSUE TITLE
#2 meetup - Saturday, 19th May

### ISSUE THREAD

**Issue by ksaitor** [SoliditySingapore/meetups#2]
📆 **Saturday, May 19th, 2018**
🕥 **11:30am**
📍 **[Lowecase](https://goo.gl/maps/XBaCiwjHmk22)**, Blk D #01-01, 1 McNally St. — It's in the middle of Lasalle college campus.

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.
> Agenda v2: Bring your public PGP key and some identity docs. We'll be doing a [Key Signing Party](https://en.wikipedia.org/wiki/Key_signing_party)

### Notes
- No free food. Bring your own money.
- If you're lost or late, please Messenger us, or [ping the chatroom](https://t.me/solidityworkshop).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is OPTIONAL (👍 here). Just join whenever you feel like it, no pressure ☕️
- tag people in comments who should be attending 😄

**Comment by weijiekoh** [comment]
Here's an idea of what we're planning to achieve with the key signing party on Saturday! http://cryptnet.net/fdp/crypto/keysigning_party/en/extra/annc-example.html

**Comment by joesarre** [comment]
Which keyserver shall we use?  My key is available on hkps.pool.sks-keyservers.net.  Fingerprint: 0x4c192084440253814ba47763247b261a7973ef95, ID: 7976ef95

**Comment by ksaitor** [comment]
@joesarre yeah, https://sks-keyservers.net seems to be pretty popular
Also, your ID seems to be `7973ef95`. Are you sure it's `7976ef95`?
