### ISSUE TITLE
#3 meetup - Saturday, 30th March

### ISSUE THREAD

**Issue by ksaitor** [SoliditySingapore/meetups#3]
📆 **Saturday, March 30th, 2019**
🕥 **11:30am**
📍 **[Twenty Eight Cafe](https://goo.gl/maps/CP1aVicjtwA2) @ 28 Wilkie Rd**

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.
> Agenda: Discuss latest tech in blockchain space
> Agenda v2: Bring your public PGP key and some identity docs if you'd like to get your keys signed like in good old days of [Key Signing Parties](https://en.wikipedia.org/wiki/Key_signing_party)

### Notes
- No free food. Bring your own money.
- If you're lost or late, please Messenger us, or [ping the chatroom](https://t.me/solidityworkshop).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSVP is Recommended (👍 here). Just join whenever you feel like it, no pressure ☕️
- tag people in comments who should be attending 😄

**Comment by weijiekoh** [comment]
Suggestion: Twenty Eight Cafe @ 28 Wilkie Rd

**Comment by Nexus7** [comment]
Shouldn’t it say 30th March?

**Comment by ksaitor** [comment]
@Nexus7 indeed! updated. March 30th

**Comment by ksaitor** [comment]
![photo_2019-03-30 15 23 56](https://user-images.githubusercontent.com/936436/55272969-e2fed380-52ff-11e9-92d3-dd1f224a5b59.jpeg)
Awesome turnout! 👏 Thank you all for mining and reaching consensus 🔗
