### ISSUE TITLE
#5 Meetup - May 7th, 2021 @ WeWork Suntec

### ISSUE THREAD

**Issue by ksaitor** [SoliditySingapore/meetups#5]
📆  May 7th, 2021
🕥  5:30pm-7:30pm
📍 WeWork @ Suntec Tower 5, 17th floor.  _Arrive at Tower 5, take escalator to 2nd floor lobby. Register. Take elevator to 17th floor._

## Agenda:
- Solidity Discussion. Introductions and a few presentations.
- Bring stickers and other crypto swag you'd like to share with the fellow nerdz.
- Bring your public PGP key and some identity docs if you'd like to get your keys signed like in good old days of [Key Signing Parties](https://en.wikipedia.org/wiki/Key_signing_party)

### Notes
- Please RSVP by  clicking 👍
- Spots are limited. But we'll try to let a bit more than 8 people. Clarifying WeWork's policies at the moment…

**Comment by ksaitor** [comment]
WeWork at Suntec (Tower 5) this Friday, May 7th 530-730pm.

I've booked the conference room for TWO hours, in case we need a projector.
Getting it for more hours might get expensive, unless we all wanna chip in some usdc :) It's ~$120/hr.

![IMG_2217](https://user-images.githubusercontent.com/936436/116861093-25104700-ac35-11eb-84a4-6a182402c6d7.JPG)

**Comment by ksaitor** [comment]
@weijiekoh @joesarre we will miss you!

**Comment by jefflam** [comment]
hi @ksaitor I'm the 8th 👍  but just wanted to check if it still fits within the 8 pax limit?

Thanks!

**Comment by ksaitor** [comment]
![image](https://user-images.githubusercontent.com/936436/117459380-e99bb280-af7d-11eb-8b98-e04d5ca16155.png)

Thank you all for coming!
