### ISSUE TITLE
#6 Meetup - Apr 02, 2022

### ISSUE THREAD

**Issue by therealyingtong** [SoliditySingapore/meetups#6]
⏰ 6pm
📍 Location:

34 Upper Weld Rd
\# 02-01
Singapore 207391
https://goo.gl/maps/3SUNm1Y36E8LuRvQA

## Agenda
- zkEVM presentation by @therealyingtong and @akshatamohanty
- (please add on!)

### Notes
- Please RSVP by clicking :+1:
- Spots are limited (10 ppl)
- Discussion: https://t.me/soliditysingapore - If you're lost or late, please msg there.

**Comment by Bernardchoo** [comment]
Hello folks ,

If you don't mind, I am happy to share about a side project I am working on - Mix & Match @ https:www.mixandmatch.space  
( currently still in test mode ) 

See you guys there :octocat:
