### ISSUE TITLE
#8 Meetup - Feb 25, 2023 - Who needs ETHDenver?

### ISSUE THREAD

**Issue by weijiekoh** [SoliditySingapore/meetups#8]
:calendar: Saturday, Feb 25th, 2023
:clock1130:  6pm
:round_pushpin: Picotin, 382 Joo Chiat Road

- No agenda, just dinner and conversations!
- No free food; pay for what you eat
- Bring stickers if you like
- RSVP by 👍  Feel free to bring your +1s
 
Tag people in comments who should be attending 😊

**Comment by joshuacheong** [comment]
Ah I would love to be there but unfortunately I am already double-booked for other arrangements. Where is best to keep updated to the next meetup?

**Comment by weijiekoh** [comment]
No worries @joshuacheong, check out our Telegram for updates: https://t.me/+TQjLlcedm8IV1gS-

**Comment by fastackl** [comment]
RSVP'd - looking forward to it cheers!

**Comment by joshuacheong** [comment]
This used to be a thing - lets make it happen in the future:
https://ethsingapore.co/

**Comment by ksaitor** [comment]
![image](https://user-images.githubusercontent.com/936436/221363424-2c78c97e-f8cc-4d55-9166-1af0ef0d5586.jpeg)

![image](https://user-images.githubusercontent.com/936436/221363430-964813ae-3097-4bae-b11b-4f3bb740c78e.jpeg)

![image](https://user-images.githubusercontent.com/936436/221363434-64d8d9a4-4377-4f06-a225-3cdba864672e.jpeg)
