### ISSUE TITLE
#9 Meetup - May 19, 2023 - Q2

### ISSUE THREAD

**Issue by ksaitor** [SoliditySingapore/meetups#9]
:calendar: Friday, May 19, 2023 - [vote here](https://t.me/c/1292422037/3494)
:clock1130: 6pm
✅  RSVP: https://lu.ma/8mwy7hze
:round_pushpin: Location will be share with approved guests only
🤔  Due to limited space we'll be giving priority to technical guests. Thank you for understanding and your support! 🙏

## Talks:
- Chainstack talk
- @weijiekoh  - Simple Private Information Retrieval (SimplePIR https://eprint.iacr.org/2022/949)
- @therealyingtong - Folding Schemes 
- @bguiz - EVM on Hedera 
- @palinatolmach - Practical Symbolic Execution for EVM

## Notes
- Bring stickers if you like
 
Tag people in comments who should be attending 😊 

## Update - event was a success
- Slides linked below
- Presentation videos are available here: https://www.youtube.com/playlist?list=PLpr9QZ8siKP1srSeNe3HZxIUK1GfAN4eq
- Upload photos in comments below

**Comment by weijiekoh** [comment]
What's the address of the Chainstack office?

**Comment by ksaitor** [comment]
> What's the address of the Chainstack office?

updated the description

**Comment by ksaitor** [comment]
Thanks to everyone who upvoted the issue. We moved our RSVPs to lu.ma this time. Please RSVP here: https://lu.ma/8mwy7hze

Thank you!

**Comment by weijiekoh** [comment]
Awesome meetup, thank you all!

Slides on SimplePIR: https://geometryresearch.github.io/simplepir-rs/

**Comment by wuzhong-zhu** [comment]
[Solidity singapore - chainstack.pptx](https://github.com/SoliditySingapore/meetups/files/11526929/Solidity.singapore.-.chainstack.pptx)

Hello friends, this is the presentation slides about Chainstack. It was great meeting all of you. Hope we meet again soon!

**Comment by palinatolmach** [comment]
Thank you all for the great meetup!

Slides on symbolic execution: [Practical Symbolic Execution for EVM—Solidity Meetup SG.pptx](https://github.com/SoliditySingapore/meetups/files/11526960/Practical.Symbolic.Execution.for.EVM.Solidity.Meetup.SG.pptx)

Here's also a recorded version of this talk from ETHTaipei: https://www.youtube.com/watch?v=sbW8fp4hMZY

**Comment by therealyingtong** [comment]
Thank you all for sharing your work at the meetup. Here are the slides I used for folding schemes: [folding schemes.pdf](https://github.com/SoliditySingapore/meetups/files/11527199/folding.schemes.pdf)

**Comment by ksaitor** [comment]
![IMG_0822](https://github.com/SoliditySingapore/meetups/assets/936436/6bf9064e-59cd-4011-81a1-59e16fd012b1)
![IMG_0824](https://github.com/SoliditySingapore/meetups/assets/936436/44332def-15bb-4901-a77c-607d22090560)
![IMG_0829](https://github.com/SoliditySingapore/meetups/assets/936436/06afb57f-0781-4eca-8a9f-ab395268a17a)
![IMG_0830](https://github.com/SoliditySingapore/meetups/assets/936436/a5cbda8c-9e51-4773-9846-8f3c50d52afa)
![IMG_0831](https://github.com/SoliditySingapore/meetups/assets/936436/e7ed001b-2749-42d2-a84f-345252c32f38)
![IMG_0838](https://github.com/SoliditySingapore/meetups/assets/936436/be9c1216-f082-4ccf-8e4a-e48febc08576)
![IMG_0840](https://github.com/SoliditySingapore/meetups/assets/936436/f3ae66fb-93cb-47ff-bc05-ce9daeee3e21)
![IMG_0843](https://github.com/SoliditySingapore/meetups/assets/936436/ec12bc28-b314-4c4c-8a69-de8ffce2bb91)
![IMG_0845](https://github.com/SoliditySingapore/meetups/assets/936436/83bbf84d-48e6-4e68-9fdb-6e3ff1988961)
![IMG_0841](https://github.com/SoliditySingapore/meetups/assets/936436/13843dc1-e710-4ea0-9d99-9b99cb2801b5)
![IMG_0848](https://github.com/SoliditySingapore/meetups/assets/936436/792d58ca-639c-4763-baea-c65568b59742)

**Comment by bguiz** [comment]
Slides from my talk: [EVM on Hedera](https://blog.bguiz.com/presentations/evm-on-hedera).
LMK if you run into any issues with the demos linked in the slides - feedback much appreciated!

- Arrows to navigate
- `F`/ `Esc` to toggle full screen
- `S` for speaker notes
